# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Roger Camara
title: Designer Estratégico
email: rogercmr@gmail.com
website: rogercamara.github.com

# Social links
twitter_username: rogercamara
github_username:  rogercamara
# dribbble_username: jekyll
facebook_username: rogercmr
# flickr_username: jekyll
instagram_username: rogercamara_
linkedin_username: rogercamara
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
Formado em Design Estratégico e pós graduado em Design de Serviços pela Universidade do Vale do Rio do Sinos. Atuo há 12 anos em projetos estratégicos de branding, serviços, produtos digitais, design de experiência e inovação tecnológica para grandes marcas e parceiros.

Utilizo os processos e ferramentas do Design Estratégico aliadas à metodologias ágeis para solucionar problemas dentro de qualquer cenário  na busca por soluções inovadoras e competitivas.
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
