# Site settings
name: Roger Camara
title: Roger Camara | Designer Estratégico - Especialista em UX
description: Designer estratégico especializado em experiîencia de usuário e inovação
url: https://rogercamara.github.io/
baseurl: ''
email: roger.camara@outlook.com
cover: https://rogercamara.github.io/img/og.png
logo: https://rogercamara.github.io/img/emojis/technologist.png
resume: https://rogercamara.github.io/resume.pdf
social:
  - title: email
    url: roger.camara@outlook.com
  - title: twitter
    url: https://twitter.com/rogercamara
  - title: instagram
    url: https://instagram.com/rogercamara_
  - title: github
    url: https://github.com/rogercamara
  - title: linkedin
    url: https://www.linkedin.com/in/rogercamara

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
